added docs in AggregateRoots, ValueObjects and entities
liwoo/malawi-meta pull request #3
Opened 2023-07-06 09:43 UTC by tauraigombera

I have added doc files for the following:
-Aggregate Roots: Constituency, GroupVillageHead, and TraditionalAuthority
-Entities: PollingCenter, Village, and ZipCode
-ValueObjects: Geolocation

2023-07-08 12:26 UTC, liwoo requested changes

2023-07-08 12:26 UTC, liwoo commented on Docs/AggregateRoots/Constituency.AggregateRoot.md
> +    public List<Constituency> GetConstituency()
`GetConstituencies` - pluralize

2023-07-08 12:26 UTC, liwoo commented on Docs/AggregateRoots/GroupVillageHead.AggregateRoot.md
> +    public List<GroupVillageHead> GetGroupVillageHead();
pluralize here as well

2023-07-08 12:26 UTC, liwoo commented on Docs/AggregateRoots/TraditionalAuthority.AggregateRoot.md
> +    public List<TraditionalAuthority> GetTraditionalAuthority()
pluralize

2023-07-08 12:26 UTC, liwoo commented on Docs/Entities/Village.Entity.md
> +
no gap here

2023-07-08 12:26 UTC, liwoo commented on Docs/ValueObjects/Geolocation.ValueObject.md
> +## Methods
you can remove the `methods` section

2023-07-08 13:43 UTC, tauraigombera commented
Resolved the requested changes

2023-07-09 18:04 UTC, liwoo approved these changes

2023-07-09 18:04 UTC, merged